### ISSUE TITLE
grpl 0.9i blotter machine

### ISSUE THREAD

**Issue by mosabalrojpany** [zeevy/grblcontroller#102]
hello zeevy how are you ?
I am in the last days of my final project and all the project working fine i have add voice command in grpl controller app and i have upload g-code file automatic and i have a last problem
the app working with grbl v1.1f and my machine working with grbl v0.9i when i connect my phone to arduino the app tell me Supports only grpl v1.1 any ide for this problem?

**Comment by zeevy** [comment]
This is not a problem app supports only 1.1 version.
There are lot of changes in communication protocol from 0.9 to 1.1

It will be easy for you to upgrade the firmware than modifying the app for 0.9
