### ISSUE TITLE
fusion 360 post process

### ISSUE THREAD

**Issue by SarkazmU** [zeevy/grblcontroller#103]
Good day. I am using Fusion 360. Post processor configuration is grbl.cps v42115. Controller GRBL firmware is up to date. But GC terminal returns "Error:20 Unsupported or invalid g-code command found in block."
Thanks in advance for help
NC is attached
[14mmGRBL_nc.txt](https://github.com/zeevy/grblcontroller/files/3100265/14mmGRBL_nc.txt)

**Comment by zeevy** [comment]
Hi
I think M6 tool change is not supported by grbl hence the error.

Thanks for using the app, in future I will try to address this issue.

Have nice time with your machine

Sent from my BlackBerry

**Comment by SarkazmU** [comment]
It is. Just tested same NC without M6 and it was all correct. Thanks again.
cannot find the "solved" button here.

**Comment by zeevy** [comment]
It just a close, no solved status in github
