### ISSUE TITLE
Scroll in the terminal window

### ISSUE THREAD

**Issue by Lenrockus** [zeevy/grblcontroller#107]
It seems that scroll , doesn't work in the terminal window. V1.25 grbl controller+ neither v1.24

**Comment by zeevy** [comment]
Thank you for reporting,
I will check, can you tell me which version of android your are using

**Comment by Lenrockus** [comment]
5.02 and 7.0

**Comment by Lenrockus** [comment]
same problem v1.26

**Comment by zeevy** [comment]
I am unable to reproduce this problem.
Tested in Android 4.4, 6, 8.1, 9
I don't have device with 7.0 or 5.02. 
I do have android 5.1 phone, i will check with that

**Comment by zeevy** [comment]
Does the scroll working for you in free version?

**Comment by Lenrockus** [comment]
Yes, it works in free version. It also works on paid version 1.23

**Comment by Lenrockus** [comment]
[https://youtu.be/bHV9P1n6624](url)
here is video of how it looks like

**Comment by zeevy** [comment]
Yes that looks like an issue with small screen mobiles.
Thanks for the video. I think I know where to fix it. 

Can you try by decreasing the display size if supported by your phone.

**Comment by Lenrockus** [comment]
Unfortunately my phones doesn't support display resizing.

**Comment by Lenrockus** [comment]
Sorry, on android 7 it is possible to decrease  display size and the scroll is working. On normal screen size it doesn't.

**Comment by zeevy** [comment]
OK, i will fix the issue soon

**Comment by zeevy** [comment]
this is fixed in free version of the application, you will get the update notification soon.
Please check and confirm the same

**Comment by zeevy** [comment]
This issue is now fixed in both paid and free version
