### ISSUE TITLE
Reasonable defaults for quick step buttons

### ISSUE THREAD

**Issue by mkraska** [zeevy/grblcontroller#112]
1. Currently, the defaults for the quick step buttons in the step/feed adjustment widget, are all zero. They might be set to 0.1, 0.3 and 1 or whatever might be useful.
2. Also, I would recommend to increase the jog speed with increasing duration of keypress. I.e. you would start with a very low speed and get increasing speed as longer as you press (a la Grbl Overseer). Min and max speed and increment should be customizable. 
1. I recommend to join the settings of the quick buttons and the max values to a single widget? They affect the same UI element anyways.

**Comment by zeevy** [comment]
Steps 1 and 3 are good idea.
Step 2 bit complicated and seems not resalable for all scenarios (may be it should be a optional feature)

**Comment by zeevy** [comment]
Implemented in recent version
