### ISSUE TITLE
File info/preview

### ISSUE THREAD

**Issue by mkraska** [zeevy/grblcontroller#113]
Before streaming a file, it would be helpful to have some feedback on the contents of that file. 
- did i open the right file
- do I use the right tool
- do I use the right stock
- where is zero expected to be?

What could be done?
- option to display the file or at least the header (possibly in an external viewer or text editor)
- compute a bounding box as in Candle. This gives a clue on zero position and stock. 
- graphical 2d preview with color coded z info. This is possibly the most challenging part

**Comment by zeevy** [comment]
Sorry to say i am not in favor implementing these features.
