### ISSUE TITLE
Остановка передачи gcode в arduino grbl

### ISSUE THREAD

**Issue by Mickle1977** [zeevy/grblcontroller#118]
![Screenshot_20200307-210643](https://user-images.githubusercontent.com/61926095/76156057-d553ef80-6105-11ea-8cd1-67c624468365.jpg)
Подскажите, что может быть не так с этим кодом?
Код сформирован в ArtCam9.
Пропуск ошибок в настройках программы включен.
![Screenshot_20200308-062937_1](https://user-images.githubusercontent.com/61926095/76156093-51e6ce00-6106-11ea-9b9f-7f3f40f992ab.jpg)
При включении данного режима, остановка происходит после первой команды.

**Comment by zeevy** [comment]
T1M6 is not supported by grbl.
What you have enabled is single step mode. What You should enable is ignore error 20
![Screenshot_20200308-090940](https://user-images.githubusercontent.com/939729/76156188-aeed7e80-611c-11ea-9835-ccfe5152f0dc.png)

**Comment by zeevy** [comment]
Also update the app to latest version

**Comment by Mickle1977** [comment]
Режим игнорирования ошибки включен. Пошаговый выключен.
В обновленной версии точно будет работать все? Новая версия платная, поэтому хотелось бы проверить работоспособность на тестовой.

**Comment by zeevy** [comment]
There seems to be a bug in free version, due to which the setting is not working. ( i just checked)
please use this promo code to download the paid version. (it may take time to fix this issue)

```
7FEGSHB28HNPG5HEGEYR8X4
```

**Comment by Mickle1977** [comment]
Спасибо.
Убрал команду T1 и все заработало
