### ISSUE TITLE
file picker stucks at /storage/emulated/0

### ISSUE THREAD

**Issue by MrDiesundas** [zeevy/grblcontroller#122]
Hi
file picker for .gcode file stucks at /storage/emulated/0.
App was enabled to access file system
Smart Phone:
Huawei Android EMUI Version 10.0.0
App Version: GRBL Controller+
Please help.
Kind Regards 
JOE
![Screenshot_20200506_154039_in co gorest grblcontroller plus](https://user-images.githubusercontent.com/64679012/81184210-70573180-8fb0-11ea-9809-1adc1cee762d.jpg)

**Comment by zeevy** [comment]
Its looks wired to me actually is should show like this

![e5412f51-e3cc-4f4d-ae57-b5dd3697e141](https://user-images.githubusercontent.com/939729/81185578-63960600-8fcf-11ea-89a8-48c486b36780.jpg)

**Comment by zeevy** [comment]
May be app has issue with android 10 version.
Can you please check in other mobile and let me know

**Comment by MrDiesundas** [comment]
thanks for fast respons.
what android version and phone do you have?
kind regards
Joe

**Comment by MrDiesundas** [comment]
android 7 and 8 works (tested on kids phone). could you investigate my issue? i can not downgrade my phone.
Joe

**Comment by zeevy** [comment]
May be issue with android 10.
Currently I don't have android 10 device to test. 
I will check this soon.

**Comment by zeevy** [comment]
Currently app runs on morethan 890 android divices with version 10, it is strange no one reported this issue

**Comment by rasanta99** [comment]
I have the same problem. I'm running it on a pocophone f1 with Android 10

**Comment by IceOnly** [comment]
I have the same Issue. On my tablet and phone. Tablet runs Android 7.1.2 and my phone (Huawei Mate 20 lite) runs android 10

EDIT:
Seems to be an issue with the file picker component:
https://github.com/nbsp-team/MaterialFilePicker/issues/114

**Comment by romadhon-razzan** [comment]
I have the same Issue, on my phone samsung Android 9 (works). but on Android 10 (not works)

**Comment by whins** [comment]
Issue is fixed with last update
Thanks
