### ISSUE TITLE
Console Send Missing

### ISSUE THREAD

**Issue by bdring** [zeevy/grblcontroller#128]
Is the console send line gone now? I don't see it.

<img src="https://user-images.githubusercontent.com/189677/99155371-f4375800-267c-11eb-8406-b63dec83e5df.jpg" width="320">

**Comment by zeevy** [comment]
May be because of your phone resolution it does not fits in the screen.
Its there just try to scroll up

**Comment by bdring** [comment]
OK, thanks. I found that.
