### ISSUE TITLE
Can I choose a line of processing? Can the cutter be cut off or the power cut off in the middle of the process?

### ISSUE THREAD

**Issue by txg5230** [zeevy/grblcontroller#134]
If the power is cut off or the knife is cut off or other reasons, the machine must start carving from scratch, which is very inconvenient and a waste of time. I don't know if this controller has this function.

**Comment by zeevy** [comment]
Paid version has that feature called job ressume. Works with absolute coordinates

**Comment by txg5230** [comment]
How to pay, I'm from China

**Comment by txg5230** [comment]
Where can I download the paid version

**Comment by zeevy** [comment]
If google play store is allowed in your country, then you can find it in the play store
Grbl Controller plus

**Comment by txg5230** [comment]
I can't use the software in our country. I like it very much. Is there any way to pay you RMB directly? Does your source file have the function of paid version?

**Comment by zeevy** [comment]
https://play.google.com/store/apps/details?id=in.co.gorest.grblcontroller.plus

The only way you can get it is from google play store. 
This source does not contain the functions of paid version

**Comment by txg5230** [comment]
China can't use Google Store, can I find someone else to download it and send it to me? Or whose account downloads who can use this application?

**Comment by txg5230** [comment]
Not downloaded from my account, can I use this app

**Comment by zeevy** [comment]
Sorry to say there is no other way to download the paid app. You have to use Google play store only may a VPN service will work for you.
If you are unable to pay for any reason, i can provide you the promo code. But still you need to download via google play store only

**Comment by txg5230** [comment]
Downloaded in the Google Store, can this app be installed on any mobile phone?

**Comment by zeevy** [comment]
Can be installed in android phones with version above 4.4 with bluetooth or usb OTG connection

**Comment by txg5230** [comment]
I downloaded the software, but one mobile phone can't install it, the other mobile phone can install it, but it doesn't work properly. Click the "open file" button, and the app will close automatically. Is APP2.68mb normal?

**Comment by zeevy** [comment]
Apk file won't be more than 3mb of size

**Comment by zeevy** [comment]
Also you can't download the paid version like that.
For free version apk you can check the releases in this repo

**Comment by txg5230** [comment]
![Screenshot_20210228_213305](https://user-images.githubusercontent.com/79130620/109420296-8c0d4780-79c9-11eb-9bfd-b10dc64a8f6a.jpg)

**Comment by txg5230** [comment]
![Screenshot_20210228_213646](https://user-images.githubusercontent.com/79130620/109420390-0c33ad00-79ca-11eb-9a60-a4449e7b92f0.jpg)

**Comment by txg5230** [comment]
The free version works well. Unable to find bgu

**Comment by txg5230** [comment]
Can only download that person to use the APP? Or where to set it before it can be used normally

**Comment by zeevy** [comment]
Sorry I am not sure what you are asking. To my knowledge grblcontroller + can be downloaded only from play store

**Comment by txg5230** [comment]
![Uploading QQ截图20210301153620.png…]()

**Comment by txg5230** [comment]
![Uploading Screenshot_20210301_155830.jpg…]()

**Comment by txg5230** [comment]
Download the app from the website you gave

**Comment by txg5230** [comment]
Click the file button APP to automatically close, unable to load the path. After several mobile phones have been replaced, this is the case in the test, and the operation of APP will automatically exit.

**Comment by txg5230** [comment]
![IMG_20210301_163703](https://user-images.githubusercontent.com/79130620/109471914-5e77db00-7a69-11eb-9b5a-717cbb7588fe.jpg)

**Comment by txg5230** [comment]
One of the mobile phones can install the APP, and the connection to Bluetooth is also successful, but all the buttons are gray

**Comment by zeevy** [comment]
If your phone does not support google play store, then app may not work properly

**Comment by zeevy** [comment]
> One of the mobile phones can install the APP, and the connection to Bluetooth is also successful, but all the buttons are gray

May be the bluetooth module is not configured for the buadrate of 115200. You need to change the bluetooth module buadrate to 115200

**Comment by txg5230** [comment]
Google withdrew from China in 2010 and could not use Google Store. It should be for this reason that it cannot be used normally. Is there any way to solve it

**Comment by zeevy** [comment]
> Google withdrew from China in 2010 and could not use Google Store. It should be for this reason that it cannot be used normally. Is there any way to solve it

Unfortunately nothing I can do in this scenario. 
May be you need to build your won with the source code

**Comment by txg5230** [comment]
Thank you very much for your answer. It is very difficult to pay for the download. It is a pity that the download is still useless. This APP is the best I have ever used. I hope the free version also adds a little more features. Development
