### ISSUE TITLE
Sainsmart 3018 Prover

### ISSUE THREAD

**Issue by ganjaninja** [zeevy/grblcontroller#138]
Hello at all.

I have a Problem to connect my hc-06 bluetooth device to my 3018 Prover.

Can not find any tutorial an the Web for this model.

I saw someone connecting the cables of the hc-06 to the place where the offline controller normally is connected.

His connection for the offline controller had 8 pins and i have 10 pins.

In the documentation, on the board  itself, or on the sainsmart hompage, i didn't find any hints or for example a wiring diagram.

Hope anyone of you can help me. 
![Screenshot_20210321-220014_Drive](https://user-images.githubusercontent.com/58890728/111920731-e19cb780-8a90-11eb-83a1-b36d2f080887.jpg)

**Comment by zeevy** [comment]
You need to find the Rx and Tx pin in the board and connect them to bluetooth module.
Rx pin of the board connects to Tx pin of bluetooth module
Tx pin of the board connects to Rx pin of bluetooth module.

If Rx and Tx pins are not exposed in the board then you may need to check any other possibilities

These may help
 https://github.com/gnea/grbl/issues/628
