### ISSUE TITLE
Manual mode, continuous movement of f value unstable machine jitter. Step increase, release the key machine can not stop immediately, always hit the machine. Can you improve?

### ISSUE THREAD

**Issue by txg5230** [zeevy/grblcontroller#139]

**Comment by zeevy** [comment]
Releasing the button will not stop the machine. Please use the stop button provided.
Use small step values when you press and holds the button

**Comment by txg5230** [comment]
Let go and stop immediately, can you? My machine stroke x1300mm, y2500mm. When moving at high speed, people's reaction is not as fast as the machine.

**Comment by zeevy** [comment]
No app is not designed for that, you can enable soft limits in the grbl which can take care of this. Or use very small jog steps. I found this method is most useful in many scenarios

**Comment by txg5230** [comment]
Let go and stop immediately, without pressing the stop button, can the app do it

**Comment by zeevy** [comment]
No, i am not interested in doing this in app. I feel current implementation is better than this
