### ISSUE TITLE
In Bluetooth mode, the engraving arc is not smooth and stuttered. Ogt mode runs smoothly. Is it the upper computer or the lower computer?

### ISSUE THREAD

**Issue by txg5230** [zeevy/grblcontroller#141]
In Bluetooth mode, the engraving arc is not smooth and stuttered. Ogt mode runs smoothly. Is it the upper computer or the lower computer?

**Comment by zeevy** [comment]
It's due to low speed of bluetooth connection.

**Comment by txg5230** [comment]
Can it be solved

**Comment by zeevy** [comment]
Unfortunately it can't be solved as the problem is with the bluetooth protocol and hardware. 

You can try increasing the buadrate of the bluetooth module and grbl firmware. But it said grbl on arduino may not be stable with higher buadrate

**Comment by txg5230** [comment]
Just tested ogt mode. It always terminates accidentally during work. The offline memory card runs normally.

**Comment by zeevy** [comment]
It can be due RF interface in USB cable from spindle or laser module.
Please use good USB cable with RF filters installed at both ends and try to keep the usb cable away from the other power cables.
use short length cable as possible

**Comment by txg5230** [comment]
![345c1162ed2c92df](https://user-images.githubusercontent.com/79130620/119262300-4035fd00-bbca-11eb-81c4-ac70a2257e16.jpg)
Buffer set to 199, will the system affect

**Comment by zeevy** [comment]
Increasing the buffer may not work. Because speed of the bluetooth module is not enough if your gcode has very short moves.
If you are running the grbl on mega or any other higher processor (not ardunio) you can try increasing the buadrate to 230400.  This has to be done in both bluethooth module and grbl firmware

**Comment by zeevy** [comment]
Increasing the buffer on arduino may cause it malfunction
