### ISSUE TITLE
Reg voice control cnc

### ISSUE THREAD

**Issue by Janaki-Ramana** [zeevy/grblcontroller#144]
Hii bro,i have done a Bluetooth cnc writing machine.can you pls provide me the voice controlled grbl controller app.pls so i can make it as voice controlled with your help.hoping that you will send the app link here or to mail.pls this is a request bro

**Comment by zeevy** [comment]
Hi Ramana, this application does not have voice control future. I remember someone has already done this (you also commented on that issue). May be @mosabalrojpany can help you on this

**Comment by Janaki-Ramana** [comment]
Bro you pls contact him@mosabalrojpany and ask to send to you.and you pls share that voice controlled apk file to me.so that i can install it.pls do help.because i cant contact him

**Comment by zeevy** [comment]
I too don't have his contact
