### ISSUE TITLE
Wemos D1 R32 ESP32 connection problem

### ISSUE THREAD

**Issue by IgorPack** [zeevy/grblcontroller#147]
Hello.

I am trying to connect this application to ESRDUINO-32 HW-729 (analogue of VeMos D1 R32 ESP32) via bluetooth. The application does not connect, the buttons are inactive. Other similar applications connect successfully via bluetooth and wifi and work.

My settings:
ESRDUINO-32 НW-729
GRBL Controller v2.56
GRBL 1.3a
SerialToserialBT | Arduino 1.8.16 (ESP32test)
Speed 115200

The question is - has anyone already done this? If yes, share your experience.
  
Thank you

**Comment by zeevy** [comment]
Can you please provide more info

- What is the baudrate of the Bluetooth module?
- What is the startup string of your grbl firmware?

Please provide the console tab output when you connected to the bluetooth module via app

I am not sure on your hardware setup, It should work if the BT baudrate is set to 15200. (8-bits, no parity, and 1-stop bit) and using official grbl firmware 1.1

**Comment by RTristani** [comment]
I have not yet gone the bluetooth route.  I am studying tje instructions tjat are included in Controller +.  That's when I found what looked like a typographical error, but wanted to make sure, so i emailed you.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: zeevy ***@***.***> Date: 12/12/21  7:07 AM  (GMT-05:00) To: zeevy/grblcontroller ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [zeevy/grblcontroller] Wemos D1 R32 ESP32 connection problem (Issue #147) 
Can you please provide more info

What is the baudrate of the Bluetooth module?
What is the startup string of your grbl firmware?

Please provide the console tab output when you connected to the bluetooth module via app

**Comment by IgorPack** [comment]
Something strange is happening. In the ESP3D web interface settings, I changed the name of the connection to "btespgrbl" and a connection with the phone and PC appeared. But other problems arose.

1. The wifi module stopped working and, as a result, there is no way to connect to the web application, ie, GRBL_ESP stopped appearing in the list of available wifi points.
2. The ability to connect via usb has disappeared, for example, the GRBL Controller does not see the usb controller.
3. When the controller is connected to different usb ports, the COM port is detected, but does not change.

As I already wrote, my settings are bluetooth speed 115200, GRBL1.3a, Arduino IDE 1.8.16. The line at the bottom of the screen Arduino IDE - ESP 2 Dev Module. Desable. Minimal SPIFFS (1.9 MB APP with OTA / 190KB SPIFFS) 240 MHz (WIFI / BT), QIO, 80MHz, 4MB (32MB). 115200. NON on COM7.

Any idea how to fix the problem?

**Comment by zeevy** [comment]
Grbl startup string "Grbl 1.1f ['$' for help]"

You can find more information here https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration

Iam not sure on the problem you are facing

**Comment by IgorPack** [comment]
Today the application finds bluetooth (apparently there was a problem with the board, or with skillful hands). There remains the question of switching to USB, the application cannot find the devices, I tried different cables, the result is the same. Any thoughts on this?

I love this app and really want to use it, but something goes wrong all the time. And yet, will there be a version for FluidNC, such as CNC Remote Control?

**Comment by zeevy** [comment]
> Today the application finds bluetooth (apparently there was a problem with the board, or with skillful hands). There remains the question of switching to USB, the application cannot find the devices, I tried different cables, the result is the same. Any thoughts on this?
> 
> I love this app and really want to use it, but something goes wrong all the time. And yet, will there be a version for FluidNC, such as CNC Remote Control?

USB I tested only with Uno R3 firmware that will work fine with arduino clones with R3 firmware.

**Comment by IgorPack** [comment]
OK, Zeevy, I get you, I'm really sorry that I can't use your application in my projects.
