### ISSUE TITLE
Jog buttons do not work

### ISSUE THREAD

**Issue by dmitriybabintsev** [zeevy/grblcontroller#150]
Hello.
I faced a pretty strange issue.. Can you please help me fix it?
When I first installed a GRBL controller it worked good (Installed on Android from Play market).
But something happened and now Jog buttons do not work at all. I don't see any output in the console window (looks like no command sent when pressing any jog button).

**Comment by zeevy** [comment]
Which connection type you are using bluetooth or usb?
Only jog buttons are not working?

**Comment by dmitriybabintsev** [comment]
I'm using Bluetooth connection.
Only jog buttons are not working. "Homing" button works on that tab.

**Comment by dmitriybabintsev** [comment]
I tried reinstalling the app but with no luck.

**Comment by dmitriybabintsev** [comment]
I should see a corresponding command in the console window when press any jog button right?

**Comment by zeevy** [comment]
> I should see a corresponding command in the console window when press any jog button right?

Yes, it should show the command.
Is there any usb connection also active like phone is connected to any other system via USB cable?

**Comment by dmitriybabintsev** [comment]
> > I should see a corresponding command in the console window when press any jog button right?
> 
> Yes, it should show the command. Is there any usb connection also active like phone is connected to any other system via USB cable?

No, only BT connection.


Looks like I found the root cause.

I just noticed that GRBL parameter $10 corrupted in my controller. Its value should be 511, but now $10=1.
All jogging commands work after I set $10=511.

Sorry for triggering a false issue..

**Comment by zeevy** [comment]
You're very welcome, thanks for the update
