### ISSUE TITLE
OTG connection

### ISSUE THREAD

**Issue by naasking** [zeevy/grblcontroller#151]
I'm having trouble establishing a USB connection. I have a bunch of Android phones, some of which I know support OTG, but I can't make the connection to grbl. I'm using an Arduino Nano with the CH340C chip which is supported from what I've read here.

I'm thinking the issue is the Y cable I made. The regular data pins are fine as my computers recognize the phone when plugged in, it just doesn't work with the phone as host. Per [this description](https://electronics.stackexchange.com/a/35468/191419), the ID pin on the cable going to the phone may be grounded internally, thus indicating it can't act as a host. Would that be correct?

I have a zillion cables so I'd rather just reuse what I have rather than buying yet another cable if I can.

**Comment by zeevy** [comment]
I am not good on these connections or wires.
As you already tried with different phones. Can you also please try with another nano or uno boards

**Comment by naasking** [comment]
The link I provided is correct. I made an OTG cable and connected the ID pin directly to ground and the OTG functionality now works. Thanks!
