### ISSUE TITLE
Application send "$10=1" when disconnecting from bluetooth

### ISSUE THREAD

**Issue by dmitriybabintsev** [zeevy/grblcontroller#154]
Hi @zeevy 
I faced a wierd issue/feature.
When I disconnect from bluetooth module by pressing ![image](https://user-images.githubusercontent.com/53568385/163771924-b7242ed7-5fcf-4b98-8a98-c8cb1f8fd471.png) button, the application always sends "$10=1" command. Next time when I turn it on I will need to manually send "$10=511" command for the application to work correctly.
Can you please tell me what is the need of sending "$10=1" command and how may I avoid this?
![image](https://user-images.githubusercontent.com/53568385/163772364-a2916a17-0959-4c08-a5a7-60458066e7d8.png)

**Comment by zeevy** [comment]
Application requires buffer report to work properly.
It sends $10=2 during startup if not already configured in firmware.

On disconnect it will try to restore the original value. As some other applications don't like $10=2
$10 only supports 0 or 1 or 2
Not sure why it needs 511 to work properly.

**Comment by zeevy** [comment]
FYI
https://github.com/zeevy/grblcontroller/issues/114

**Comment by dmitriybabintsev** [comment]
> Application requires buffer report to work properly. It sends $10=2 during startup if not already configured in firmware.
> 
> On disconnect it will try to restore the original value. As some other applications don't like $10=2 $10 only supports 0 or 1 or 2 Not sure why it needs 511 to work properly.

He @zeevy 
Thanks for your reply.
$10=1 and $10=2 make very poor info in the status messages.
In grblHAL there're lots of options available in $10 parameter:
![image](https://user-images.githubusercontent.com/53568385/163942956-57e2193c-ec30-436d-a55d-40f87d938ea4.png)

If I set $10=1 or $10=2, I will not get info about speed, spindel, position coordinates etc. That's why I need a higher debug level in grblHAL firmware.
And it looks strange for me that the application tries to modify GRBL settings implicitely. Can we somehow avoid this?

**Comment by zeevy** [comment]
Unfortunately it can't be avoided for now, as the application is build with grbl 1.1 compatibility.
I will try to change the behavior in upcoming releases

**Comment by dmitriybabintsev** [comment]
I'm closing the issue in this case, thanks @zeevy
