### ISSUE TITLE
Problem with GRBL controller and Sculptfun S10

### ISSUE THREAD

**Issue by Prcharnay** [zeevy/grblcontroller#159]
I have a problem with a laser engraver sculptfun S10 that I can’t solve. I want to use GRBL controller with this laser and it don’t work. I use an Android tablet with Android 11. When I use laser GRBL with a window machine or Lightburn with a Mac my laser Sculptfun works perfectly, but with GRBL controller and an USB connection nothing happen. I have the following message  « device not supported » do you think it’s a firmware problem can you help me or do I need to contact Sculptfun ?

**Comment by zeevy** [comment]
USB connection has limited hardware support.
If the hardware board is Arduino UNO then app needs UNO R3 firmware in the serial chip.
If its a manufacturer custom board then chips/devices listed here are supported https://github.com/felHR85/UsbSerial
