### ISSUE TITLE
Add support for ESP32 GRBL controller 

### ISSUE THREAD

**Issue by mathojojo** [zeevy/grblcontroller#160]
Hello,

I tried the app, but couldn't connect to USB (nothing happen when I conenct it). I suppose it's because my CNC's controller is a ESP32 (Spark-Concept, xPro v5). On site, I only see mentions to arduino controllers.

Would it be possible to add esp32 drivers ??

Thank you

**Comment by zeevy** [comment]
USB connection has limited supports, because it depends on another opensource lib. https://github.com/felHR85/UsbSerial
