### ISSUE TITLE
 I would like the paid version on an old phone

### ISSUE THREAD

**Issue by dannab** [zeevy/grblcontroller#161]
Hello
I would like to buy a paid version
but unfortunately google play tells me that
my Huawei p9 lite with android 7 is not compatible ,
the free version works perfectly with that phone and Grbl_Esp32,
 I made works of over 750000 lines without any problem.

is there any way to get the paid version?

Best regards

**Comment by zeevy** [comment]
Hi I don't have any clue on this now. the only additional permission added for paid version is `<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />` (added to support the bluetooth LE)

that may be the problem.
