### ISSUE TITLE
Frame Button (like LaserGRBL for windows)

### ISSUE THREAD

**Issue by NandoGommez** [zeevy/grblcontroller#163]
would it be possible to add a "frame" button, so that it can help locate the recording point?

Or a button to configure macro, where you can add a gcode, in LaserGRBL for windows the "Frame" button has a gcode configured, which captures and calculates the radius and size of the image to be engrave.

**Comment by zeevy** [comment]
App supports custom buttons, where you can provide gcode supported by grbl firmware only. App does not intercept the gcode sent to the firmware. So it does not do any calculations
