### ISSUE TITLE
Can't connect to xPro V5 

### ISSUE THREAD

**Issue by TJSCustoms** [zeevy/grblcontroller#172]
I've got a CNC xPro V5 controller running FluidNC 3.7, and have run gcode through UGS successfully. I have an older Samsung tablet with Android 8, that I connected with an OTG adaptor and it seems to connect and show data from my controller in the terminal tab but the buttons do not activate to allow me to jog the machine or even load a file. Any suggestions?

**Comment by zeevy** [comment]
It will work only with grbl firmware 1.1
