### ISSUE TITLE
Check WCS with MCS

### ISSUE THREAD

**Issue by Drevene** [zeevy/grblcontroller#175]
I am using your GRBL Controller ver. 2.56 in tablet Android ver. 12 for controlling the CNC milling machine 3018. Sometimes, for unknown reasons, it happens during work that the work position and machine position are different. The machine moves outside the working area. I don't know if some command has been lost or if one operation has not completed and another command has already been sent. The result is that the material is destroyed and there is a risk of serious damage to the machine. I would like to set the mode so that the work position and machine position are checked after each operation. I have a single step mode set. I set the GRBL parameter $10=3, but it is hard-coded to 2. Now I have to watch the machine work for long hours and turn it off in case of problems so that it doesn't get destroyed. The material and its several days of preparation are lost. Please tell  me ASAP how to solve this problem.
![IMG_2023](https://github.com/zeevy/grblcontroller/assets/146917603/5f869567-aec4-4b70-ab93-46bd9477421b)

**Comment by zeevy** [comment]
Looks like stepper motors are skipping the steps, you may need to check the hardware.

Work position and machine position can be different, depends on the coordinate system you are working on (G54, G55, G56, etc..)

Please check if reported machine position is matches with machine actual physical position or not.

In single step mode application will stop sending the gcode if single gcode command is lost in transmission. Same applicable for non single step mode also ( app has its won tracking of sent command size, if it does not receives ok from firmware, app buffer will be full and will stop sending gcode )

Application requires buffer report to work properly.
It sends $10=2 during startup if not already configured in firmware.

I advice you to use any other sender to trouble shoot the problem
