### ISSUE TITLE
ESP32 FluidNC Compatibility 

### ISSUE THREAD

**Issue by AndreiVoian** [zeevy/grblcontroller#176]
Hello! I'm using an ESP32 with FluidNC firmware. Is this configuration compatible with grblcontroller ? If not, could you please advise on how I can adapt the ESP32 to work with your application?

**Comment by zeevy** [comment]
No it will not work


________________________________
From: AndreiVoian ***@***.***>
Sent: Wednesday, January 10, 2024 12:51:28 PM
To: zeevy/grblcontroller ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zeevy/grblcontroller] ESP32 FluidNC Compatibility (Issue #176)


Hello! Can we use an ESP32 that has FluidNC with this application?

**Comment by AndreiVoian** [comment]
Will grblHAL work?

**Comment by zeevy** [comment]
May be not it's designed only for grbl 1.1f


________________________________
