### ISSUE TITLE
TCP connection support

### ISSUE THREAD

**Issue by jelinj8** [zeevy/grblcontroller#177]
Would it be possible to add support for connecting via TCP/IP? I have a ESP-M2 board with WiFi/UART bridge firmware, used to connect my machine with Lightburn (it is a laser). Until now it seems to be more reliable than BT module and it can be used with a desktop PC, BT was occasionally loosing data and scrambling the job. Lightburn uses fixed port 23 (telnet), but configurable value would be better. Thanks.

**Comment by zeevy** [comment]
Currently I can't spend time on this, happy accept the pull request if any one does
