### ISSUE TITLE
It won't let me use it 

### ISSUE THREAD

**Issue by Danixxdd** [zeevy/grblcontroller#178]
Download the application through APKPure but it won't let me use it. I connect to the HC-05 but I can't do anything. I need help, please. 
![Screenshot_2024-05-12-20-26-34-171_in co gorest grblcontroller](https://github.com/zeevy/grblcontroller/assets/169626205/508a6ccd-4a91-49b6-88f4-47f38b26ec04)
![Screenshot_2024-05-12-20-26-35-883_in co gorest grblcontroller](https://github.com/zeevy/grblcontroller/assets/169626205/57fb32f3-9d41-49e5-97a7-3eba2d0a66d3)

**Comment by zeevy** [comment]
You can download the aab file from here https://github.com/zeevy/grblcontroller/releases

Looks like your firmware is not supported, application supports only grbl 1.1f

You can check your firmware or any other error messages in console tab

**Comment by Danixxdd** [comment]
What can I do to solve this problem please help

**Comment by zeevy** [comment]
This app works only with grbl 1.1f firmware, if you have old one then you have two options
1. carefully upgrade to 1.1f
2. leave the old device as is, buy new board and flash grbl 1.1f

More information of upgrading the firmware or flashing new will be available in grbl repo
