### ISSUE TITLE
spindle button

### ISSUE THREAD

**Issue by Lenrockus** [zeevy/grblcontroller#44]
spindle button doesn't work, but command m3,m5 works ok.

**Comment by zeevy** [comment]
Yes,
For security reasons in grbl firmware starting or stopping spindle is not allowed during machine running or idle state.  
It only works when machine is in hold state

**Comment by Lenrockus** [comment]
Could you please make this function available in any state? Maybe adding security option in setting menu?

**Comment by zeevy** [comment]
Not possible its not the this app limitation. This security feature is enforced in grbl firmware itself.
You can use custom button feature for this
