### ISSUE TITLE
Wishes | Gcode list sorting | Gcode list search

### ISSUE THREAD

**Issue by Lenrockus** [zeevy/grblcontroller#52]
Could you please add support for older devices on android 4.0 - 4.2. Also more custom buttons would be a good idea and search option in gcode list or at least sorting possibility. Thank you.

**Comment by zeevy** [comment]
It may not work properly with older devices.
Also older devices has very small screen where ui won't fit properly. 
Even I don't have android mobile with older version to build and test the application. 

I will check with other options, in upcoming release

**Comment by zeevy** [comment]
Search and gcode file sorting is added now. Additionally full file picker is added ( which supports internal storage)
