### ISSUE TITLE
Cant download it

### ISSUE THREAD

**Issue by saeed477** [zeevy/grblcontroller#73]
I cant download it because of otg. Please fix it .thanks.

**Comment by zeevy** [comment]
You may need to update the serial firware on the arduino board. Try with latest board with uno R3 firmware.
Chech this thread 
https://github.com/zeevy/grblcontroller/issues/64

**Comment by saeed477** [comment]
Thanks for your feedback.
But i cant update my grbl controller from google play store. Because my phome (g2 mini) doesnt have otg device and play store sayed your device dosnt support this version.

**Comment by zeevy** [comment]
I think i missed your point. Min software requirement for app is androod 4.4 kitkat.
Which version of android you have?

**Comment by saeed477** [comment]
Android 5.0.1 official

**Comment by saeed477** [comment]
Old version (without otg ) works well. But play store doesnt primission to update.

**Comment by zeevy** [comment]
I am not sure what problem you are facing.
If you are not able update the app through play store, then you can install the apk directly from git hub release page

**Comment by zeevy** [comment]
https://github.com/zeevy/grblcontroller/releases/tag/2.2.8

**Comment by saeed477** [comment]
Thanks.
Thats evry thing that I need. Sorry I'm not pro in githup and use mobile so I didnt see that. Thanks.
