### ISSUE TITLE
Can the minimum size of jog be set to 0.01mm/step?

### ISSUE THREAD

**Issue by viewsat** [zeevy/grblcontroller#97]
Can the minimum size of jog be set to 0.01mm/step?
Because I need to use a thin piece of paper to measure the position of the X-axis and the Y-axis and the z-axis, this 0.1mm/step unit is too large, and must be accurately adjusted with 0.01mm/step.

**Comment by zeevy** [comment]
No unfortunately min resolution is 0.1

Quick work around would be by using custom buttons

**Comment by viewsat** [comment]
The jog minimum resolution of all CNC controllers has a unit of 0.01mm or less. I hope the grblcontroller can add this, which is very important for operating the cnc machine.
Because there are only four custom buttons, X+, X-, Y+, Y-, Z+, Z-, a total of six custom buttons are used.

**Comment by zeevy** [comment]
Frankly i never came across this requirement i too use paper for z calibration 0.1mm is enough for me.

I will try to add this in upcoming release.

**Comment by viewsat** [comment]
Thank you very much for your quick response. I am doing some metal cnc engraving work, so I often use jog 0.01/step. I am very happy that you can try to add it in the upcoming version.

**Comment by zeevy** [comment]
Implemented in version 2.35
