### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it.   Searched Location: 

### ISSUE THREAD

**Issue by 1107979819** [zeevy/grblcontroller#98]
error message:

File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
/Users/rain/Android/grblcontroller/app/src/nullnull/debug/google-services.json
/Users/rain/Android/grblcontroller/app/src/debug/nullnull/google-services.json
/Users/rain/Android/grblcontroller/app/src/nullnull/google-services.json
/Users/rain/Android/grblcontroller/app/src/debug/google-services.json
/Users/rain/Android/grblcontroller/app/src/nullnullDebug/google-services.json
/Users/rain/Android/grblcontroller/app/google-services.json

**Comment by zeevy** [comment]
You should get your own services.json file from firebase console using your google account.
