### ISSUE TITLE
Manual movement Z axis

### ISSUE THREAD

**Issue by bourdoul** [zeevy/grblcontroller#99]
Hi, everybody.
I have version 2.35 (free) Not working manual movement along the axis Z. With this problem I'm not alone. The developer is sending everyone here.

**Comment by zeevy** [comment]
Can you provide more details.
If only z axis is not working then may be you have chosen 0 as step size. 

Please go through the documentation available in the application about section. 

If you can provide more details or images that will really help in trouble shooting

**Comment by zeevy** [comment]
And FYI this is the right place to report any problems that you may face with the application.

Doing so you are actually helping others who may have similar problem and contributing to the application. This is how open source applications works

**Comment by bourdoul** [comment]
Connection via Bluetooth (HC-4 module). Through other programs everything works correctly. Moving along other axes works. The settings "Jogging max step size Z" are set to step 10. I went through different options, but this parameter does not affect the performance. The Home command works correctly-movements on the Z axis are started.

**Comment by zeevy** [comment]
What is the grbl firmware version?

**Comment by bourdoul** [comment]
1.1f

**Comment by bourdoul** [comment]
Arduino Nano + CNC shield Board. And if I enter g-code manually (G0 Z1 or G0 Z-1), then the movements are normal.

**Comment by zeevy** [comment]
Can you please share the screenshot of console window in the applicatipn.

Also axis move buttons uses jog commands not gcode commands. 

In recent version application has separate jog step bar for z axis, may be you forgot to adjust that. 

Also please share the console output appears after pressing the jog button. 

If your grbl is not custom version and it is supported by app then it will print the grbl version, settings as soon as it  connets

**Comment by bourdoul** [comment]
![screenshot_2019-02-17-12-18-25](https://user-images.githubusercontent.com/47698674/52911097-631d2c80-32b0-11e9-8a65-cc8993552dba.png)
![screenshot_2019-02-17-12-18-45](https://user-images.githubusercontent.com/47698674/52911098-631d2c80-32b0-11e9-9fda-1c62a497471a.png)
![screenshot_2019-02-17-12-21-06-1](https://user-images.githubusercontent.com/47698674/52911100-63b5c300-32b0-11e9-8184-0714f398ab8b.jpg)
![screenshot_2019-02-17-12-21-57-1](https://user-images.githubusercontent.com/47698674/52911101-63b5c300-32b0-11e9-9f89-977fc99195bb.jpg)
![screenshot_2019-02-17-12-18-18](https://user-images.githubusercontent.com/47698674/52911102-63b5c300-32b0-11e9-9c3c-6a751071bf79.png)

**Comment by bourdoul** [comment]
Understood! Thanks for your help. The manual does not say anything how to call the menu "Jogging step and feed".  The menu is called by briefly pressing the line "Step Size|JogFeed"

**Comment by zeevy** [comment]
Ok i got the problem
You are adjusting the max size of the step bar not choosing the step value. 

You can choose the step value in jogiing control panel it self. Click on the text "Step Size | Jog Feed" text that is just above the jog buttons. You can get a dialog to adjust z step size, xy step size and jog feed

**Comment by zeevy** [comment]
Yes you are right, manual is not upto date and it is not fully documented. I will look into that when i gets time

**Comment by bourdoul** [comment]
Thank you for your prompt assistance!

**Comment by zeevy** [comment]
Error 2 that you are getting i am not sure about that. May some noice is picked up and interfacing the serial comunication.
If your getting that only in startup then you can ignore it but if it appears in between the job app will stop the steaming.

**Comment by bourdoul** [comment]
Another question. Is it possible to make the screen not go off when the application is running?

**Comment by zeevy** [comment]
Its not a good idea it will drain the battery. Application will work even screen locked.
If you need screen to be on during the job then you can do that in your phone display settings.

**Comment by zeevy** [comment]
The option of keeping the screen on is now added in settings.
